<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Retro Red Car',
                'code' => '10000000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/cars-img1.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 6,
                'classification_id' => 9,
                'material_id' => 24,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Retro Tiffany Car',
                'code' => '10000001',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/cars-img2.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 6,
                'classification_id' => 9,
                'material_id' => 24,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Retro mini Red Car',
                'code' => '10000003',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/cars-img3.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 6,
                'classification_id' => 9,
                'material_id' => 24,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Retro Chevrolet Car',
                'code' => '10000004',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/cars-img4.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 6,
                'classification_id' => 9,
                'material_id' => 24,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Retro Gray Rocket Car',
                'code' => '10000005',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/cars-img5.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 6,
                'classification_id' => 9,
                'material_id' => 24,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Historical Bowl',
                'code' => '10000006',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/carvings-img1.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 5,
                'classification_id' => 9,
                'material_id' => 23,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Historical Jeen dish',
                'code' => '10000007',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/carvings-img2.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 5,
                'classification_id' => 9,
                'material_id' => 23,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Wonderful Paintings',
                'code' => '10000008',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/paintings-img1.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 1,
                'classification_id' => 1,
                'material_id' => 2,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Beautiful Paintings',
                'code' => '10000009',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/paintings-img2.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 1,
                'classification_id' => 1,
                'material_id' => 2,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Handmade Clock',
                'code' => '10000010',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/sculptures-img1.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 4,
                'classification_id' => 8,
                'material_id' => 15,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Silver Coin',
                'code' => '10000011',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/sculptures-img2.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 4,
                'classification_id' => 4,
                'material_id' => 14,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ],
            [
                'name' => 'Gold Coin',
                'code' => '10000012',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus cum doloremque facere illum iusto libero necessitatibus quisquam quos. Ipsa, praesentium.',
                'author' => fake()->firstName . ' ' . fake()->lastName,
                'image' => 'image/sculptures-img4.jpg',
                'price' => rand(1000, 15000),
                'auction_date' => now()->addDays(rand(1, 30)),
                'category_id' => 4,
                'classification_id' => 4,
                'material_id' => 13,
                'status_id' => 1,
                'year' => rand(1900, 2021),
            ]
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}

